function goTo(page){const target=$(page);if(!target)return;if(target.classList.contains('staff-only')&&!isStaff())page='dashboard';if(target.classList.contains('admin-only')&&!isAdmin())page='dashboard';qsa('.page').forEach(p=>p.classList.remove('active'));$(page)?.classList.add('active');qsa('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const names={dashboard:'Visão geral',tickets:'Chamados','new-ticket':'Novo chamado',reports:'Relatórios',users:'Usuários',settings:'Configurações'};setText('pageTitle',names[page]||'Central de Serviços');setText('breadcrumbPage',names[page]||'');$('sidebar')?.classList.remove('open');if(page==='tickets')renderTickets();if(page==='reports')renderReports();if(page==='users')renderUsers();window.scrollTo({top:0,behavior:'smooth'});}
function clearTicketFilters(){['ticketSearch','statusFilter','priorityFilter','departmentFilter'].forEach(id=>{if($(id))$(id).value='';});renderTickets();}
function exportCSV(){const rows=tickets.map(t=>[t.code,t.subject,t.requester?.full_name||'',t.department?.name||departmentName(t.department_id),t.category,PRIORITY_LABEL[t.priority],STATUS_LABEL[t.status],t.technician?.full_name||'',t.location||'',t.equipment||'',t.asset_tag||'',formatDateTime(t.created_at),formatDateTime(t.updated_at)]),headers=['Protocolo','Assunto','Solicitante','Secretaria','Categoria','Prioridade','Status','Técnico','Local','Equipamento','Patrimônio','Abertura','Atualização'],quote=v=>`"${String(v??'').replaceAll('"','""')}"`,csv='\ufeff'+[headers,...rows].map(r=>r.map(quote).join(';')).join('\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`chamados-ti-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);}
function updateSlaPreview(){const p=document.querySelector('select[name="priority"]')?.value||'media';setText('newTicketSlaPreview',`${SLA_HOURS[p]} hora${SLA_HOURS[p]===1?'':'s'}`);}
function bindTicketRows(root){root.querySelectorAll('[data-ticket]').forEach(row=>row.addEventListener('click',()=>openTicket(row.dataset.ticket)));}
function bindModalClose(){qsa('[data-modal-close]').forEach(b=>b.addEventListener('click',closeModal));$('modalRoot')?.querySelector('[data-close-modal]')?.addEventListener('click',e=>{if(e.target.hasAttribute('data-close-modal'))closeModal();});}
function closeModal(){$('modalRoot').innerHTML='';}

function slaState(t){if(['resolvido','cancelado'].includes(t.status))return{state:'done',label:'Finalizado'};const due=new Date(t.sla_due_at||new Date(new Date(t.created_at).getTime()+SLA_HOURS[t.priority]*3600000)),ms=due-new Date();if(ms<=0)return{state:'overdue',label:`Atrasado ${humanDuration(Math.abs(ms))}`};const total=SLA_HOURS[t.priority]*3600000;if(ms<=Math.max(3600000,total*.25))return{state:'risk',label:`${humanDuration(ms)} restantes`};return{state:'ok',label:`${humanDuration(ms)} restantes`};}
function slaChip(t){const s=slaState(t);return`<span class="sla-chip ${s.state}">${esc(s.label)}</span>`;}
function isResolvedWithinSla(t){const end=new Date(t.resolved_at||t.updated_at||0),due=new Date(t.sla_due_at||0);return end<=due;}
function queueScore(t){const p={critica:400,alta:300,media:200,baixa:100}[t.priority]||0,s={overdue:80,risk:50,ok:0}[slaState(t).state]||0;return p+s;}
function priorityBadge(p){return`<span class="badge prio-${p}">${esc(PRIORITY_LABEL[p]||p)}</span>`;}function statusBadge(s){return`<span class="badge status-${s}">${esc(STATUS_LABEL[s]||s)}</span>`;}
function isStaff(){return['technician','admin'].includes(currentProfile?.role);}function isAdmin(){return currentProfile?.role==='admin';}
function departmentName(id){return departments.find(d=>d.id===id)?.name||'—';}
function groupBy(list,getKey){const map=new Map();list.forEach(item=>{const key=getKey(item)||'Não informado';map.set(key,(map.get(key)||0)+1);});return[...map.entries()].sort((a,b)=>b[1]-a[1]);}
function humanDuration(ms){const min=Math.max(0,Math.round(ms/60000));if(min<60)return`${min} min`;const h=Math.floor(min/60),m=min%60;if(h<24)return m?`${h}h ${m}m`:`${h}h`;const d=Math.floor(h/24),rh=h%24;return rh?`${d}d ${rh}h`:`${d}d`;}
function relativeDate(iso){if(!iso)return'—';const ms=new Date()-new Date(iso);if(ms<60000)return'agora';if(ms<3600000)return`há ${Math.floor(ms/60000)} min`;if(ms<86400000)return`há ${Math.floor(ms/3600000)} h`;if(ms<604800000)return`há ${Math.floor(ms/86400000)} d`;return formatDate(iso);}
function formatDate(iso){return iso?new Date(iso).toLocaleDateString('pt-BR'):'—';}function formatDateTime(iso){return iso?new Date(iso).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—';}
function firstName(name){return String(name||'Usuário').trim().split(/\s+/)[0];}function getInitials(name){return String(name||'U').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();}
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function setText(id,value){if($(id))$(id).textContent=value;}
function emptyRow(cols,title){return`<tr><td colspan="${cols}"><div class="empty-state"><strong>${esc(title)}</strong><span>Nenhum registro para exibir.</span></div></td></tr>`;}
function setButtonLoading(btn,loading,text){if(!btn)return;btn.disabled=loading;btn.textContent=text;}
function friendlyAuthError(error){const msg=String(error?.message||'').toLowerCase();if(msg.includes('invalid login'))return'E-mail ou senha incorretos.';if(msg.includes('email not confirmed'))return'Confirme seu e-mail antes de entrar.';return'Não foi possível entrar. Confira seus dados e tente novamente.';}
function toast(message,type=''){const root=$('toastRoot');if(!root)return;const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=message;root.appendChild(el);setTimeout(()=>el.remove(),3200);}
function readLocal(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}function persistDemo(){if(demoMode)localStorage.setItem(DEMO_KEY,JSON.stringify({tickets}));}

function demoDepartments(){return[
  {id:'dep-adm',name:'Administração',acronym:'SEMAD',active:true},{id:'dep-saude',name:'Saúde',acronym:'SEMUS',active:true},{id:'dep-edu',name:'Educação',acronym:'SEMED',active:true},{id:'dep-assist',name:'Assistência Social',acronym:'SEMAS',active:true},{id:'dep-fin',name:'Finanças',acronym:'SEMF',active:true},{id:'dep-agri',name:'Agricultura',acronym:'SEMAGRI',active:true},{id:'dep-cult',name:'Cultura',acronym:'SEMCULT',active:true},{id:'dep-infra',name:'Infraestrutura',acronym:'SEMINFRA',active:true},{id:'dep-gab',name:'Gabinete',acronym:'GAB',active:true}
];}
function seedDemoUsers(){return[
  {id:'demo-admin',full_name:'Dill',role:'admin',active:true,department_id:'dep-adm',department:{name:'Administração'},created_at:new Date(Date.now()-120*86400000).toISOString()},
  {id:'demo-tech',full_name:'Técnico de Suporte',role:'technician',active:true,department_id:'dep-adm',department:{name:'Administração'},created_at:new Date(Date.now()-80*86400000).toISOString()},
  {id:'demo-saude',full_name:'Usuário Saúde',role:'requester',active:true,department_id:'dep-saude',department:{name:'Saúde'},created_at:new Date(Date.now()-40*86400000).toISOString()}
];}
function seedDemoTickets(){const deps=demoDepartments(),mk=(n,subject,dep,priority,status,hoursAgo,category,requester='Servidor Municipal')=>{const created=new Date(Date.now()-hoursAgo*3600000),due=new Date(created.getTime()+SLA_HOURS[priority]*3600000),resolved=status==='resolvido'?new Date(Math.min(Date.now(),created.getTime()+Math.max(1,SLA_HOURS[priority]-.5)*3600000)):null;return{id:`demo-ticket-${n}`,code:`TI-2026-${String(10000+n).padStart(5,'0')}`,requester_id:'demo-saude',requester:{full_name:requester},department_id:dep,department:deps.find(d=>d.id===dep),technician_id:status==='aberto'?null:'demo-admin',technician:status==='aberto'?null:{full_name:'Dill'},subject,description:`Solicitação de demonstração: ${subject}. Registro criado para validar o fluxo profissional da Central de Serviços de T.I.`,category,priority,status,contact:null,location:'Sede / Unidade',equipment:null,asset_tag:null,sla_due_at:due.toISOString(),created_at:created.toISOString(),updated_at:(resolved||new Date()).toISOString(),resolved_at:resolved?.toISOString()||null,demo_events:[{id:crypto.randomUUID(),event_type:'created',message:'Chamado registrado.',internal:false,created_at:created.toISOString(),author:requester}],demo_attachments:[]};};return[
  mk(1,'Servidor sem acesso à rede','dep-adm','critica','atendimento',3.4,'Servidor','Setor de T.I.'),mk(2,'Internet instável no CRAS','dep-assist','alta','aberto',5.5,'Internet / Rede','Recepção CRAS'),mk(3,'Impressora da secretaria offline','dep-edu','media','atendimento',10,'Impressora','Secretaria de Educação'),mk(4,'Instalação de certificado digital','dep-adm','baixa','aguardando',20,'Sistema / Software','Setor de Compras'),mk(5,'Computador da recepção não liga','dep-saude','alta','resolvido',30,'Computador / Notebook','UBS Centro'),mk(6,'Configurar e-mail institucional','dep-agri','baixa','resolvido',60,'E-mail / Acesso','Agricultura'),mk(7,'Câmera externa sem imagem','dep-gab','media','aberto',4,'Câmeras / CFTV','Gabinete')
];}